baseURL = "https://eskyna.com/"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = false
title = "Natalia Kleemann | Style & Image Coaching"

[languages]
  [languages.de]
    languageCode = "de-DE"
    languageName = "Deutsch"
    weight = 1
    contentDir = "content"
    [languages.de.params]
      author = "Natalia Kleemann"
      description = "Style- und Image-Coaching für Menschen, die sichtbar, stilsicher und authentisch auftreten wollen."
  
  [languages.ru]
    languageCode = "ru-RU"
    languageName = "Русский"
    weight = 2
    contentDir = "content/ru"
    [languages.ru.params]
      author = "Natalia Kleemann"
      description = "Благодаря индивидуальному image-коучингу вы станете уверенны и привлекательны."

[params]
  author = "Natalia Kleemann"
  description = "Style- und Image-Coaching für Menschen, die sichtbar, stilsicher und authentisch auftreten wollen."
